module.exports = {
  purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        black: "#000000",
        white: "#ffffff",
        lightGrey: "#dfdfdf",
        primary: "#ffc593",
        secondary: "#bc7198",
        tertiary: "#5a77ff",
      },
      backgroundImage: () => ({
        create: "url('/images/home/desktop/create-and-share.jpg')",
        "create-md": "url('/images/home/tablet/create-and-share.jpg')",
        "create-sm": "url('/images/home/mobile/create-and-share.jpg')",
        stories: "url('/images/home/desktop/beautiful-stories.jpg')",
        "stories-md": "url('/images/home/tablet/beautiful-stories.jpg')",
        "stories-sm": "url('/images/home/mobile/beautiful-stories.jpg')",
        designed: "url('/images/home/desktop/designed-for-everyone.jpg')",
        "designed-md": "url('/images/home/tablet/designed-for-everyone.jpg')",
        "designed-sm": "url('/images/home/mobile/designed-for-everyone.jpg')",
        mountains: "url('/images/stories/desktop/mountains.jpg')",
        "mountains-sm": "url('/images/stories/mobile/mountains.jpg')",
        cityscapes: "url('/images/stories/desktop/cityscapes.jpg')",
        "cityscapes-sm": "url('/images/stories/mobile/cityscapes.jpg')",
        voyage: "url('/images/stories/desktop/18-days-voyage.jpg')",
        "voyage-sm": "url('/images/stories/mobile/18-days-voyage.jpg')",
        architecturals: "url('/images/stories/desktop/architecturals.jpg')",
        "architecturals-sm": "url('/images/stories/mobile/architecturals.jpg')",
        tour: "url('/images/stories/desktop/world-tour.jpg')",
        "tour-sm": "url('/images/stories/mobile/world-tour.jpg')",
        corners: "url('/images/stories/desktop/unforeseen-corners.jpg')",
        "corners-sm": "url('/images/stories/mobile/unforeseen-corners.jpg')",
        king: "url('/images/stories/desktop/king-on-africa.jpg')",
        "king-sm": "url('/images/stories/mobile/king-on-africa.jpg')",
        trip: "url('/images/stories/desktop/trip-to-nowhere.jpg')",
        "trip-sm": "url('/images/stories/mobile/trip-to-nowhere.jpg')",
        rage: "url('/images/stories/desktop/rage-of-the-sea.jpg')",
        "rage-sm": "url('/images/stories/mobile/rage-of-the-sea.jpg')",
        running: "url('/images/stories/desktop/running-free.jpg')",
        "running-sm": "url('/images/stories/mobile/running-free.jpg')",
        waves: "url('/images/stories/desktop/behind-the-waves.jpg')",
        "waves-sm": "url('/images/stories/mobile/behind-the-waves.jpg')",
        calm: "url('/images/stories/desktop/calm-waters.jpg')",
        "calm-sm": "url('/images/stories/mobile/calm-waters.jpg')",
        milky: "url('/images/stories/desktop/milky-way.jpg')",
        "milky-sm": "url('/images/stories/mobile/milky-way.jpg')",
        forest: "url('/images/stories/desktop/dark-forest.jpg')",
        "forest-sm": "url('/images/stories/mobile/dark-forest.jpg')",
        somwarpet: "url('/images/stories/desktop/somwarpet.jpg')",
        "somwarpet-sm": "url('/images/stories/mobile/somwarpet.jpg')",
        dreams: "url('/images/stories/desktop/land-of-dreams.jpg')",
        "dreams-sm": "url('/images/stories/mobile/land-of-dreams.jpg')",
        moon: "url('/images/stories/desktop/moon-of-appalacia.jpg')",
        "moon-md": "url('/images/stories/tablet/moon-of-appalacia.jpg')",
        "moon-sm": "url('/images/stories/mobile/moon-of-appalacia.jpg')",
        hero: "url('/images/features/desktop/hero.jpg')",
        "hero-md": "url('/images/features/tablet/hero.jpg')",
        "hero-sm": "url('/images/features/mobile/hero.jpg')",
        hero2: "url('/images/pricing/desktop/hero.jpg')",
        "hero2-md": "url('/images/pricing/tablet/hero.jpg')",
        "hero2-sm": "url('/images/pricing/mobile/hero.jpg')",
        beta: "url('/images/shared/desktop/bg-beta.jpg')",
        "beta-md": "url('/images/shared/tablet/bg-beta.jpg')",
        "beta-sm": "url('/images/shared/mobile/bg-beta.jpg')",
      }),
      spacing: {
        34: "34px",
        60: "60px",
        270: "270px",
        280: "280px",
        288: "288px",
        294: "294px",
        317: "317px",
        375: "375px",
        490: "490px",
        500: "500px",
        600: "600px",
        650: "650px",
      },
    },
  },
  variants: {
    extend: {
      display: ["group-hover"],
      backgroundColor: ["checked"],
    },
  },
  plugins: [],
};
