export const stories = [
  {
    date: "April 16th 2020",
    title: "The Mountains",
    images: "md:bg-mountains bg-mountains-sm",
    name: "John Appleseed",
  },
  {
    date: "April 14th 2020",
    title: "Sunset Cityscapes",
    images: "md:bg-cityscapes bg-cityscapes-sm",
    name: "Benjamin Cruz",
  },
  {
    date: "April 11th 2020",
    title: "18 Days Voyage",
    images: "md:bg-voyage bg-voyage-sm",
    name: "Alexei Borodin",
  },
  {
    date: "April 9th 2020",
    title: "Architecturals",
    images: "md:bg-architecturals bg-architecturals-sm",
    name: "Samantha Brooke",
  },
  {
    date: "April 7th 2020",
    title: "World Tour 2019",
    images: "md:bg-tour bg-tour-sm",
    name: "Timothy Wagner",
  },
  {
    date: "April 3rd 2020",
    title: "Unforeseen Corners",
    images: "md:bg-corners bg-corners-sm",
    name: "William Malcolm",
  },
  {
    date: " March 29th 2020",
    title: "King on Africa: Part II",
    images: "md:bg-king bg-king-sm",
    name: "Tim Hillenburg",
  },
  {
    date: "March 21st 2020",
    title: "The Trip to Nowhere",
    images: "md:bg-trip bg-trip-sm",
    name: "Felicia Rourke",
  },
  {
    date: "March 19th 2020",
    title: "Rage of The Sea",
    images: "md:bg-rage bg-rage-sm",
    name: "Mohammed Abdul",
  },
  {
    date: "March 16th 2020",
    title: "Running Free",
    images: "md:bg-running bg-running-sm",
    name: "Michelle",
  },
  {
    date: "March 11th 2020",
    title: "Behind the Waves",
    images: "md:bg-waves bg-waves-sm",
    name: "Lamarr Wilson",
  },
  {
    date: "March 9th 2020",
    title: "Calm Waters",
    images: "md:bg-calm bg-calm-sm",
    name: "Samantha Brooke",
  },
  {
    date: "March 5th 2020",
    title: "The Milky Way",
    images: "md:bg-milky bg-milky-sm",
    name: "Benjamin Cruz",
  },
  {
    date: "March 4th 2020",
    title: "Night at The Dark Forest",
    images: "md:bg-forest bg-forest-sm",
    name: "Mohammed Abdul",
  },
  {
    date: "March 1st 2020",
    title: "Somwarpet’s Beauty",
    images: "md:bg-somwarpet bg-somwarpet-sm",
    name: "Michelle",
  },
  {
    date: "February 25th 2020",
    title: "Land of Dreams",
    images: "md:bg-dreams bg-dreams-sm",
    name: "William Malcolm",
  },
];
